
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARENTESIS_ABIERTO = 25;
  public static final int CHARACTER = 21;
  public static final int SLASH = 13;
  public static final int END = 16;
  public static final int VARIABLE = 23;
  public static final int SEMI_COLON = 19;
  public static final int UPPER = 9;
  public static final int SEPARATOR = 12;
  public static final int COLON = 18;
  public static final int NO_OR_MORE = 4;
  public static final int PORCENTAGE = 17;
  public static final int BEGIN = 15;
  public static final int PARENTESIS_CERRADO = 24;
  public static final int COMMA = 11;
  public static final int LOWER = 8;
  public static final int ONE_OR_MORE = 5;
  public static final int MAYOR = 14;
  public static final int EOF = 0;
  public static final int DISJUNCTION = 3;
  public static final int SET = 7;
  public static final int CONCATENATION = 2;
  public static final int error = 1;
  public static final int SPECIAL = 22;
  public static final int TEXT = 20;
  public static final int NO_OR_ONE = 6;
  public static final int NUMBERS = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONCATENATION",
  "DISJUNCTION",
  "NO_OR_MORE",
  "ONE_OR_MORE",
  "NO_OR_ONE",
  "SET",
  "LOWER",
  "UPPER",
  "NUMBERS",
  "COMMA",
  "SEPARATOR",
  "SLASH",
  "MAYOR",
  "BEGIN",
  "END",
  "PORCENTAGE",
  "COLON",
  "SEMI_COLON",
  "TEXT",
  "CHARACTER",
  "SPECIAL",
  "VARIABLE",
  "PARENTESIS_CERRADO",
  "PARENTESIS_ABIERTO"
  };
}

