
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIAGONAL = 11;
  public static final int SLASH_MENOR = 9;
  public static final int SLASH_MAYOR = 10;
  public static final int PUNTO_Y_COMA = 37;
  public static final int CORCHETE_CERRADO = 16;
  public static final int DOUBLE = 4;
  public static final int RESTA = 18;
  public static final int PIE = 47;
  public static final int DOS_PUNTOS = 8;
  public static final int PARENTESIS_ABIERTO = 13;
  public static final int CADENAS = 34;
  public static final int IGUAL = 30;
  public static final int BARRAS = 46;
  public static final int COLUMN = 31;
  public static final int COMMA = 12;
  public static final int ARROBA = 7;
  public static final int TITULO = 39;
  public static final int SUMA = 17;
  public static final int MIN = 27;
  public static final int MEDIANA = 23;
  public static final int NUMERO_FLOTANTE = 35;
  public static final int CORCHETE_ABIERTO = 15;
  public static final int EOF = 0;
  public static final int ARREGLO = 6;
  public static final int error = 1;
  public static final int PROGRAM = 33;
  public static final int PIE_2 = 52;
  public static final int CADENA = 5;
  public static final int VALUES = 44;
  public static final int EJE_Y = 41;
  public static final int MODULO = 21;
  public static final int EJE_X = 40;
  public static final int MODA = 24;
  public static final int VARIABLE = 3;
  public static final int BARRAS_2 = 50;
  public static final int LINEA_2 = 51;
  public static final int VARIANZA = 25;
  public static final int END = 32;
  public static final int PARENTESIS_CERRADO = 14;
  public static final int MEDIA = 22;
  public static final int EXEC = 38;
  public static final int LABEL = 45;
  public static final int DIVISION = 20;
  public static final int LINEA = 48;
  public static final int MAX = 26;
  public static final int TITULO_Y = 43;
  public static final int NUMERO_ENTERO = 36;
  public static final int HISTOGRAM = 49;
  public static final int TITULO_X = 42;
  public static final int VAR = 2;
  public static final int PRINT = 29;
  public static final int CONSOLE = 28;
  public static final int MULTIPLICACION = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "VARIABLE",
  "DOUBLE",
  "CADENA",
  "ARREGLO",
  "ARROBA",
  "DOS_PUNTOS",
  "SLASH_MENOR",
  "SLASH_MAYOR",
  "DIAGONAL",
  "COMMA",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MODULO",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN",
  "CONSOLE",
  "PRINT",
  "IGUAL",
  "COLUMN",
  "END",
  "PROGRAM",
  "CADENAS",
  "NUMERO_FLOTANTE",
  "NUMERO_ENTERO",
  "PUNTO_Y_COMA",
  "EXEC",
  "TITULO",
  "EJE_X",
  "EJE_Y",
  "TITULO_X",
  "TITULO_Y",
  "VALUES",
  "LABEL",
  "BARRAS",
  "PIE",
  "LINEA",
  "HISTOGRAM",
  "BARRAS_2",
  "LINEA_2",
  "PIE_2"
  };
}

